openapi: "3.0.0"
info:
  version: 1.0.0
  title: Xoo OpenAPI Backend
servers:
  - url: https://openapi.cn-north.lc.example.com/
    description: Production server
  - url: https://stg-openapi.cn-north.lc.example.com/
    description: Staging server for testing / release.
  - url: http://localhost:8080/
    description: Local server for development
paths:
  /player/current:
    get:
      summary: Request user for current user.
      tags:
        - Player
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: XUser
components:
  securitySchemes:
    leancloudAuth:
      type: http
      scheme: bearer
      bearerFormat: LeanCloud
  schemas:
    XUser:
      type: object
      required:
        - objectId
        - userId
        - nickname
        - avatarUrl
      properties:
        objectId:
          type: string
        userId:
          type: string
        nickname:
          type: string
        avatarUrl:
          type: string
security:
  - leancloudAuth: []
