openapi: "3.0.0"
info:
  version: 1.0.0
  title: OpenAPI Backend
servers:
  - url: https://openapi.cn-north.lc.example.com/
    description: Production server
  - url: https://stg-openapi.cn-north.lc.example.com/
    description: Staging server for testing / release.
  - url: http://localhost:8080/
    description: Local server for development
paths:
  /user/current:
    get:
      summary: Request user for current user.
      tags:
        - User
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  securitySchemes:
    leancloudAuth:
      type: http
      scheme: bearer
      bearerFormat: LeanCloud
  schemas:
    User:
      type: object
      required:
        - userId
        - nickname
      properties:
        objectId:
          type: string
        userId:
          type: string
        nickname:
          type: string
security:
  - leancloudAuth: []
