/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.example.openapi_server.api

import com.example.openapi_server.model.XUser
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.*

@Validated
@RequestMapping("\${api.base-path:}")
interface UserApi {

    @GetMapping(
        value = ["/user/current"],
        produces = ["application/json"]
    )
    fun userCurrentGet(): ResponseEntity<XUser> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
